name: statuskeep
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^0.2.0+1
  flutter_file_utils: ^0.1.1+5
  gallery_saver: ^2.0.1
  permission_handler: ^5.0.1+1
  google_fonts: ^1.1.0
  built_value: ^7.1.0
  flutter_vector_icons: ^0.2.1
  auto_route: ^0.6.7
  device_info: ^0.4.2+6
  flushbar: ^1.10.4
  logger: ^0.9.2
  states_rebuilder: ^2.3.1
  pull_to_refresh: ^1.6.1
  path_provider: ^1.6.11
  video_player: ^0.10.11+2
  video_thumbnail: ^0.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  esys_flutter_share: ^1.0.2
  mime: ^0.9.7
  package_info: ^0.4.1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0
  flutter_launcher_icons: ^0.7.5
  auto_route_generator: ^0.6.8
  built_value_generator: ^7.1.0
  build_runner: ^1.10.0

dependency_overrides:
  analyzer: 0.39.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/google_fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
